# Generated by Django 3.2.16 on 2024-10-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25, unique=True, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
                'ordering': ('breed',),
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Кличка')),
                ('color', models.CharField(max_length=25, verbose_name='Цвет')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Полный возраст в месяцах')),
                ('description', models.TextField(verbose_name='Описание')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.breed', verbose_name='Порода')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'котенок',
                'verbose_name_plural': 'котята',
                'ordering': ('name',),
                'default_related_name': 'cats',
            },
        ),
    ]
