# Generated by Django 3.2.16 on 2024-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='slug',
            field=models.SlugField(default=0, max_length=25, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
