# Generated by Django 3.2.16 on 2024-10-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_breed_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',), 'verbose_name': 'порода', 'verbose_name_plural': 'породы'},
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='breed',
            new_name='name',
        ),
    ]
