# Generated by Django 3.2.16 on 2024-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_cat_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_cat_name'),
        ),
    ]
