# Generated by Django 3.2.16 on 2024-10-01 12:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0005_cat_unique_owner_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Серый', 'Серый'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Рыжий', 'Рыжий'), ('Смешанный', 'Смешанный')], max_length=25, verbose_name='Цвет'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='cats.cat', verbose_name='Котенок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ('cat__name',),
                'default_related_name': 'scores',
            },
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('cat', 'user'), name='unique_user_cat'),
        ),
    ]
