# Generated by Django 3.2.16 on 2024-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_auto_20241001_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
